app:
  project_name: Notes API
  code: notes-api
  version: 1.0.3
  db:
    server: mysql_server
    username: root
    password: dbpsswrd
    name: notes
  auth:
    key_path: data/key.pem
  notes:
    table:
      notes: notes
      tags: tags
      notes_tags_links: notes_tags

http:
  enabled: true
  port: 80
