app:
  project_name: Notes API
  code: notes-api
  env: dev
  version: 1.0.0
db:
  server: notes_db
  username: {secret_db_username}
  password: {secret_db_password}
  name: notes
http:
  enabled: true
  port: 80